# Elyra extensions doesn't fetch the secrets that are exposed to Jupyter Notebook out of the box. Therefore, when you want to run your Notebook as a Pipeline by utilizing Elyra extension, 
# you have to provide the secret names and keys from Elyra configuration. 
# This policy helps you to pick the secrets that have a certain label, and expose them 
# to the pipelineRuns at runtime.
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: inject-secret-envvar
spec:
  rules:
  - name: inject-secret-envvar
    match:
      any:
      - resources:
          kinds:
          - PipelineRun
    context:
      - name: secretlist
        apiCall:
          urlPath: "/api/v1/namespaces/{{request.namespace}}/secrets?labelSelector=opendatahub.io%2Fdashboard%3Dtrue"
          jmesPath: "items[].metadata.name"
    mutate:
      foreach:
      - list: secretlist
        foreach:
          - list: "request.object.spec.pipelineSpec.tasks"
            patchesJson6902: |-
              - path: "/spec/pipelineSpec/tasks/{{elementIndex1}}/taskSpec/steps/0/envFrom/-"
                op: add
                value:
                  secretRef:
                    name: "{{element0}}"
